name:                danibot
version:             0.2.0.0
license:             BSD3
author:              "Leonidas Loucas"
maintainer:          "lloucas@purestorage.com"
copyright:           "2020 Leonidas Loucas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README <https://stash-ir.dev.purestorage.com:7999/~lloucas/ciri-bot.git#readme>

dependencies:
- base                  >= 4        && < 5   
- transformers
- wreq
- network
- websockets
- wuss
- aeson
- bytestring
- text
- lens
- lens-aeson
- monoid-subclasses
- containers
- conceit
- attoparsec
- stm
- async
- foldl
- streaming

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -Wall

executables:
  danibot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - danibot
